const GET_TASKS = "GET_TASKS";
const GET_TASKS_SUCCESS = "GET_TASKS_SUCCESS";
const GET_TASKS_FAILURE = "GET_TASKS_FAILURE";
const CREATE_TASK = "CREATE_TASK";
const CREATE_TASK_SUCCESS = "CREATE_TASK_SUCCESS";
const CREATE_TASK_FAILURE = "CREATE_TASK_FAILURE";
const ARCHIVE_TASK = "ARCHIVE_TASK";
const ARCHIVE_TASK_SUCCESS = "ARCHIVE_TASK_SUCCESS";
const ARCHIVE_TASK_FAILURE = "ARCHIVE_TASK_FAILURE";
const GET_ARCHIVE_TASK = "GET_ARCHIVE_TASKS";
const UPDATE_TASK = "UPDATE_TASK";
const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS";
const UPDATE_TASK_FAILURE = "UPDATE_TASK_FAILURE";
const TASK_MODAL_ACTION = "TASK_MODAL_ACTION";
const GET_ARCHIVE_TASK_SUCCESS = "GET_ARCHIVE_TASK_SUCCESS";
const GET_ARCHIVE_TASK_FAILURE = "GET_ARCHIVE_TASK_FAILURE";
const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";
const DELETE_TASK_FAILURE = "DELETE_TASK_FAILURE";
const RESTORE_FROM_ARCHIVE_SUCCESS = "RESTORE_FROM_ARCHIVE_SUCCESS";
const RESTORE_FROM_ARCHIVE_FAILURE = "RESTORE_FROM_ARCHIVE_FAILURE";
const TODO = "TODO";
const IN_PROGRESS = "IN_PROGRESS";
const COMPLETED = "COMPLETED";
const GET_TASK_DETAIL = "GET_TASK_DETAIL";
const PRIORITY_HIGH = "PRIORITY_HIGH";
const PRIORITY_LOW = "PRIORITY_LOW";
const PRIORITY_MEDIUM = "PRIORITY_MEDIUM";

//filter & sorts

const FILTER_TODAY_DEADLINE = "FILTER_TODAY_DEADLINE";
const FILTER_BEFORE_TODAY_DEADLINE = "FILTER_BEFORE_TODAY_DEADLINE";
const FILTER_THIS_WEEK = "FILTER_THIS_WEEK";
const FILTER_THIS_MONTH = "FILTER_THIS_MONTH";

const FILTER = "FILTER";
const SORT = "SORT";

const GET_TAGS_SUCCESS = "GET_TAGS_SUCCESS";
const GET_TAGS_FAILURE = "GET_TAGS_FAILURE";

const PRIORITY_HIGH_TO_LOW = "PRIORITY_HIGH_TO_LOW";
const PRIORITY_LOW_TO_HIGH = "PRIORITY_LOW_TO_HIGH";
const NEAREST_DEADLINE = "NEAREST_DEADLINE";
const FARTHEST_DEADLINE = "FARTHEST_DEADLINE";

const FILTER_BY_TAGS = "FILTER_BY_TAGS";

const taskState = {
  tasks: [],
  kanban: { TODO: [], IN_PROGRESS: [], COMPLETED: [] },
  archivedTasks: [],
  openTaskModal: false,
  editTask: null,
  error: null,
  loading: false,
  taskDetail: null,
  selectedFilter: null,
  tags: [],
};
const kanbanInitial = { TODO: [], IN_PROGRESS: [], COMPLETED: [] };

export {
  taskState,
  GET_TASKS,
  CREATE_TASK,
  ARCHIVE_TASK,
  GET_ARCHIVE_TASK,
  CREATE_TASK_SUCCESS,
  CREATE_TASK_FAILURE,
  ARCHIVE_TASK_SUCCESS,
  ARCHIVE_TASK_FAILURE,
  GET_TASKS_FAILURE,
  GET_TASKS_SUCCESS,
  UPDATE_TASK,
  UPDATE_TASK_FAILURE,
  UPDATE_TASK_SUCCESS,
  TASK_MODAL_ACTION,
  TODO,
  IN_PROGRESS,
  COMPLETED,
  GET_TASK_DETAIL,
  kanbanInitial,
  FILTER_TODAY_DEADLINE,
  FILTER_BEFORE_TODAY_DEADLINE,
  FILTER,
  FILTER_THIS_WEEK,
  FILTER_THIS_MONTH,
  PRIORITY_HIGH,
  PRIORITY_LOW,
  PRIORITY_MEDIUM,
  PRIORITY_HIGH_TO_LOW,
  PRIORITY_LOW_TO_HIGH,
  NEAREST_DEADLINE,
  FARTHEST_DEADLINE,
  SORT,
  GET_ARCHIVE_TASK_SUCCESS,
  GET_ARCHIVE_TASK_FAILURE,
  DELETE_TASK_SUCCESS,
  DELETE_TASK_FAILURE,
  RESTORE_FROM_ARCHIVE_FAILURE,
  RESTORE_FROM_ARCHIVE_SUCCESS,
  GET_TAGS_FAILURE,
  GET_TAGS_SUCCESS,
  FILTER_BY_TAGS,
};
