const GET_TASKS = "GET_TASKS";
const GET_TASKS_SUCCESS = "GET_TASKS_SUCCESS";
const GET_TASKS_FAILURE = "GET_TASKS_FAILURE";
const CREATE_TASK = "CREATE_TASK";
const CREATE_TASK_SUCCESS = "CREATE_TASK_SUCCESS";
const CREATE_TASK_FAILURE = "CREATE_TASK_FAILURE";
const ARCHIVE_TASK = "ARCHIVE_TASK";
const ARCHIVE_TASK_SUCCESS = "ARCHIVE_TASK_SUCCESS";
const ARCHIVE_TASK_FAILURE = "ARCHIVE_TASK_FAILURE";
const GET_ARCHIVE_TASK = "GET_ARCHIVE_TASKS";
const UPDATE_TASK = "UPDATE_TASK";
const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS";
const UPDATE_TASK_FAILURE = "UPDATE_TASK_FAILURE";
const TASK_MODAL_ACTION = "TASK_MODAL_ACTION";
const TODO = "TODO";
const IN_PROGRESS = "IN_PROGRESS";
const COMPLETED = "COMPLETED";
const GET_TASK_DETAIL = "GET_TASK_DETAIL";

const taskState = {
  tasks: [],
  kanban: { TODO: [], IN_PROGRESS: [], COMPLETED: [] },
  archivedTasks: [],
  openTaskModal: false,
  editTask: null,
  error: null,
  loading: false,
  taskDetail: null,
};
const kanbanInitial = { TODO: [], IN_PROGRESS: [], COMPLETED: [] };

export {
  taskState,
  GET_TASKS,
  CREATE_TASK,
  ARCHIVE_TASK,
  GET_ARCHIVE_TASK,
  CREATE_TASK_SUCCESS,
  CREATE_TASK_FAILURE,
  ARCHIVE_TASK_SUCCESS,
  ARCHIVE_TASK_FAILURE,
  GET_TASKS_FAILURE,
  GET_TASKS_SUCCESS,
  UPDATE_TASK,
  UPDATE_TASK_FAILURE,
  UPDATE_TASK_SUCCESS,
  TASK_MODAL_ACTION,
  TODO,
  IN_PROGRESS,
  COMPLETED,
  GET_TASK_DETAIL,
  kanbanInitial,
};
